FROM tensorflow/tensorflow
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
RUN set -ex && \
    pip install numpy pandas scipy pika 
RUN pip install paho-mqtt scikit-learn
CMD ["python","-u","proxy.py"]